version: '3.8'

services:
  web:
    image: "priyanshu1979/taskmanager:03"
    container_name: "task_manager"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: task_db
    ports:
      - "5000:5000"
    volumes:
      - .:/task

    networks:
      - net-task
    depends_on:
      - mysql


  mysql:
    image: "mysql:latest"
    container_name: "task_database"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - task:/var/lib/mysql
    networks:
      - net-task

networks:
  net-task:
    driver: bridge


volumes:
  task:
    external: false

